name: Interfass
version: '1.0-SNAPSHOT'
main: io.realmit.interfass.Interfass
api-version: '1.21'

commands:
  interfass:
    description: Open the Interfass interface
    usage: /interfass
    permission: interfass.command.main

  teleport:
    description: Open the Interfass teleport interface
    usage: /teleport
    permission: interfass.command.teleport

permissions:
  interfass.command.main:
    description: Allows using /interfass:interfass
    default: true

  interfass.command.teleport:
    description: Allows using /interfass:teleport
    default: op

  interfass.menu.teleport:
    description: Allows opening the Interfass teleport menu
    default: op