name: Interfass
version: '1.0-SNAPSHOT'
main: io.realmit.interfass.Interfass
api-version: '1.21'

commands:
  interfass:
    description: Open the Interfass interface
    usage: /interfass
    permission: interfass.command.main

  teleport:
    description: Open the Interfass teleport interface
    usage: /teleport
    permission: interfass.command.teleport

  quest:
    description: Open the Interfass quest interface
    usage: /quest
    permission: interfass.command.quest

  negative:
    description: Open the Interfass quest interface
    usage: /negative
    permission: interfass.command.negative

permissions:
  interfass.command.main:
    description: Allows using /interfass:interfass
    default: true

  interfass.command.teleport:
    description: Allows using /interfass:teleport
    default: true

  interfass.menu.teleport:
    description: Allows opening the Interfass teleport menu
    default: true

  interfass.menu.quest:
    description: Allows opening the Interfass quest menu
    default: true

  interfass.menu.negative:
    description: Allows opening the Interfass negative menu
    default: true